### ISSUE TITLE
Playground example error

### ISSUE THREAD

**Issue by adamsoffer** [UniversalLogin/UniversalLoginSDK#130] opened 2018-10-31 17:30 UTC
I recently watched @alexvandesande's talk on universal logins and I'm super excited about this project! I went to check out the [example app](https://universal-login-example.netlify.com/) and noticed an error and wanted to bring it to your attention.

After creating an ID the loader spins perpetually. I'm seeing this in the console

```
POST https://universal-login-relayer.herokuapp.com/identity 500 (Internal Server Error)
asyncToGenerator.js:20 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
```

**Comment by Kyrrui** [comment] 2018-10-31 17:59
Ah yes, your probably used an upper case character in the name, thanks for pointing out this issue, I know how to fix and will make a PR since I fixed this for our hackathon project

**Comment by marekkirejczyk** [comment] 2018-11-06 11:00
Should be fixed by now. Let us know if you can reproduce.

**Closed** 2018-11-26 18:34 UTC
