### ISSUE TITLE
[Bug] Example is not working

### ISSUE THREAD

**Issue by antoineherzog** [UniversalLogin/UniversalLoginSDK#133] opened 2018-11-04 11:27 UTC
Hi Everyone

I tried to run the example

https://universal-login-example.netlify.com/

But it seems it is not working. I have We are creating your new ID, please wait a minute...

Forever..

Thank you!

Antoine

**Comment by Kyrrui** [comment] 2018-11-05 15:43
Hey @antoineherzog, I believe this to be a duplicate of issue #130, closing for now.

**Closed by Kyrrui** 2018-11-05 15:43 UTC
